languageCode:           "en"
title:                  "Ceres Icons"
baseURL:                "https://icons.agrista.com"
enableInlineShortcodes: true
enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_site"

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false

module:
  mounts:
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "SVG icon library for Agrista Ceres"
  social_image_path:    /assets/img/bootstrap-icons-social.png

  package_version:      "1.0.0-alpha"
  package_repo:         "https://github.com/agrista/ceres-icons"

  current_version:      "4.4.1"
  docs_version:         "4.4"

  main:                 "https://agrista.com"
  repo:                 "https://github.com/agrista/ceres"
  twitter:              "agrista"
  icons:                "https://icons.agrista.com"
